title: Simons Notes
description: Big data and coding adventures.

author: Simon Streubel
url: http://simnotes.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
# - title: About
#   url: /about
# - title: Contact
#   url: /contact

social:
   github: simnotes
   twitter: 
   facebook: simon.espunkt
   email: simnotes@gmail.com

google_analytics: ""
